name: Monitoring Workflow

on: push

jobs:
  monitor:
    runs-on: ubuntu-latest

    steps:
      - name: Start
        run: echo "Monitoring started"

      - name: System Info
        run: uname -a

      - name: Disk Usage
        run: df -h

      - name: End
        run: echo "Monitoring finished"
